---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    role: director
    {{- include "sorry-cypress.labels" . | nindent 4 }}
  name: director
spec:
  replicas: 1
  selector:
    matchLabels:
      role: director
      {{- include "sorry-cypress.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        role: director
        {{- include "sorry-cypress.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: director
        image: "{{ .Values.images.director.repository }}:{{ .Values.images.director.tag }}"
        imagePullPolicy: {{ .Values.images.director.pullPolicy }}
        ports:
        - containerPort: 1234
        envFrom:
        - configMapRef:
            name: director
        resources: {}
status: {}
