---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    role: api
    {{- include "sorry-cypress.labels" . | nindent 4 }}
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      role: api
      {{- include "sorry-cypress.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        role: api
        {{- include "sorry-cypress.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: api
        image: "{{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}"
        imagePullPolicy: {{ .Values.images.api.pullPolicy }}
        ports:
        - containerPort: 4000
        envFrom:
        - configMapRef:
            name: api
        resources: {}
status: {}
