---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    role: mongo
    {{- include "sorry-cypress.labels" . | nindent 4 }}
  name: mongo
spec:
  containers:
  - name: mongo
    image: "{{ .Values.images.mongo.repository }}:{{ .Values.images.mongo.tag }}"
    imagePullPolicy: {{ .Values.images.mongo.pullPolicy }}
    ports:
    - containerPort: 27017
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
