---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    role: api
    {{- include "sorry-cypress.labels" . | nindent 4 }}
  name: api
spec:
  ports:
  - port: {{ .Values.service.api.port }}
    protocol: TCP
    targetPort: 4000
  selector:
    role: api
    {{- include "sorry-cypress.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.api.type }}
status:
  loadBalancer: {}