---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    role: mongo
    {{- include "sorry-cypress.labels" . | nindent 4 }}
  name: mongo
spec:
  ports:
  - port: {{ .Values.service.mongodb.port }}
    protocol: TCP
    targetPort: 27017
  selector:
    role: mongo
    {{- include "sorry-cypress.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.mongodb.type }}
status:
  loadBalancer: {}
