---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    role: director
    {{- include "sorry-cypress.labels" . | nindent 4 }}
  name: director
spec:
  ports:
  - port: {{ .Values.service.director.port }}
    protocol: TCP
    targetPort: 1234
  selector:
    role: director
    {{- include "sorry-cypress.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.director.type }}
status:
  loadBalancer: {}